"""initial schema: users and conversations

对 `create_all()` 早先已经在建的两张表（`User`/`Conversation`）拍一份基线快照。
这本身没有改变现在这份仓库的实际启动行为——`db/engine.py` 的 `init_db()`
仍然用 `SQLModel.metadata.create_all`，图快、不用先跑 `alembic upgrade head`
才能起服务。这份基线的意义在于：从下一次真的要改字段（加列、改约束、加表）
开始，改动应该走 `alembic revision --autogenerate` 生成新版本，而不是直接
改 `db/models.py` 然后指望 `create_all` 神奇地把已有数据库也改对——
`create_all` 只会建"不存在的表"，不会给已有表加新列，这正是它当初
被点名"schema 演进故事弱"的原因。

Revision ID: 0001
Revises:
Create Date: 2026-09-20
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_thread_id'), 'conversation', ['thread_id'], unique=True)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_thread_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
